# Generated by Django 4.2.7 on 2023-11-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ucitel',
            options={'verbose_name': 'Učiteľ', 'verbose_name_plural': 'Učitelia'},
        ),
    ]
