# Generated by Django 4.2.7 on 2024-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0006_alter_kruzok_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='datum_narodenia',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
