# Generated by Django 4.2.7 on 2024-04-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0007_student_datum_narodenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucitel',
            name='datum_narodenia',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='mesto',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='psc',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='ulica',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
